### ISSUE TITLE
Can't open locally. Lack of dependencies?

### ISSUE THREAD

**Issue by hessam-kk** [a99jafari/task-manager#1]
I tried to download the source using `git clone`  and  run it from my computer, but it does not open correctly. what happen when I open `index.html ` is shown in the following screenshot... I guess I just don't have right dependencies, but I couldn't find anything in `Readme`. 
it works fine in [https://todo.jafari.dev](https://todo.jafari.dev)
please help, thanks.

![2021-06-15 02 11 13  d9fe27807e4a](https://user-images.githubusercontent.com/24957423/121963148-f8486700-cd7e-11eb-8b0f-3daac02dbb3a.jpg)

**Comment by jafari-dev** [comment]
@Hessam-Koucheki 
Hi Hessam,
Thanks for informing me about this issue. Your problem is that CORS in your browser is blocked by default. To resolve this problem, you can enable the CORS in your browser.

If you are using Firefox, follow these steps To enable CORS:
1. Open Firefox, and on the address bar, type about:config.
2. Click on I'll be careful,I promise!".
3. Search for security.fileuri.strict_origin_policy.
4. Right-click and select Toggle to change the value from true to false.
5. Close the browser and launch it again.

I search a little and didn't find any way to enabling CORS in Chrome. But I just found some extensions for this purpose. But we don't want to resolve the problem using any external tools.

I pushed a new commit on the project and resolved the CORS. Now, Please clone the project one time again, I think your problem will be resolve by my last commit.

**Comment by hessam-kk** [comment]
Hi, 
Thanks it now works fine...
I just download the new version and it's working. 
Thank You!
